### ISSUE TITLE
panic: illegal line number for file

### ISSUE THREAD

**Issue by visstro** [nokia/ntt#359]
Hi,

I just tried playing around with the project to check TTCN3 support in VS Code.
TTCN3 sources are loosely divided into files with functions, constants, and tests in different directories.

Jumping to definition is either not working (first 83 lines of the file) or causing a language server crash (line >83).
The number 83 seems to be consistent across different files.

Log output from VSCode:
```logs
Activating TTCN-3 Language Server...
Installed TTCN-3 Language Server version: 0.11.1
Checking GitHub for the latest release...found version 0.11.1
toolsPath: /HOMEDIR/.vscode-server/bin/HASH/bin:REST_OF_THE_PATH
Scanning "file:///HOMEDIR/WORKSPACE_PATH" for possible TTCN-3 suites
File "file:///HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn" does not belong to any known test suite
Scanning "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" for possible TTCN-3 suites
Could not find a good candidate. Trying "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" recursively and hope for the best.
Adding "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" to list of known test suites
panic: illegal line number for file "/HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn". got=90, max=83

goroutine 25 [running]:
github.com/nokia/ntt/internal/loc.(*File).LineStart(0xc00007a6c0, 0x5a)
	/home/runner/work/ntt/ntt/internal/loc/position.go:222 +0x1b9
github.com/nokia/ntt/internal/ntt.(*ParseInfo).Pos(0xc00002e0a0, 0xc000108460, 0x11)
	/home/runner/work/ntt/ntt/internal/ntt/parse.go:58 +0x3b
github.com/nokia/ntt/internal/ntt.(*Suite).DefinitionAt(0xc000108230, {0xc000108460, 0x62}, 0x6a5ba1, 0x7c6800)
	/home/runner/work/ntt/ntt/internal/ntt/identifier.go:28 +0x68
github.com/nokia/ntt/internal/lsp.(*Server).definition(0xc000110b68, {0xa3, 0xb0}, 0xc000110b40)
	/home/runner/work/ntt/ntt/internal/lsp/definition.go:24 +0x15b
github.com/nokia/ntt/internal/lsp.(*Server).Definition(0xc000168000, {0x7be558, 0xc0000f0ac0}, 0x6ad340)
	/home/runner/work/ntt/ntt/internal/lsp/server_gen.go:32 +0x25
github.com/nokia/ntt/internal/lsp/protocol.serverDispatch({0x7be558, 0xc0000f0ac0}, {0x7c6a58, 0xc0000fe380}, 0xc000146270, {0x7be638, 0xc0000f0a80})
	/home/runner/work/ntt/ntt/internal/lsp/protocol/tsserver.go:283 +0x14f7
github.com/nokia/ntt/internal/lsp/protocol.ServerHandler.func1({0x7be558, 0xc0000f0ac0}, 0xc000146270, {0x7be638, 0xc0000f0a80})
	/home/runner/work/ntt/ntt/internal/lsp/protocol/protocol.go:62 +0x90
github.com/nokia/ntt/internal/lsp/jsonrpc2.MustReplyHandler.func1({0x7be558, 0xc0000f0ac0}, 0xc0000ba3a8, {0x7be638, 0xc0000f0a80})
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:35 +0xf6
github.com/nokia/ntt/internal/lsp/jsonrpc2.AsyncHandler.func1.2()
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:101 +0x83
created by github.com/nokia/ntt/internal/lsp/jsonrpc2.AsyncHandler.func1
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:99 +0x1a5
[Info  - 5:43:35 PM] Connection to server got closed. Server will restart.
[Error - 5:43:35 PM] Request textDocument/definition failed.
Error: Connection got disposed.
	at Object.dispose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
Scanning "file:///HOMEDIR/WORKSPACE_PATH" for possible TTCN-3 suites
File "file:///HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn" does not belong to any known test suite
Scanning "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" for possible TTCN-3 suites
Could not find a good candidate. Trying "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" recursively and hope for the best.
Adding "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" to list of known test suites
panic: illegal line number for file "/HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn". got=90, max=83

goroutine 34 [running]:
github.com/nokia/ntt/internal/loc.(*File).LineStart(0xc00007ac00, 0x5a)
	/home/runner/work/ntt/ntt/internal/loc/position.go:222 +0x1b9
github.com/nokia/ntt/internal/ntt.(*ParseInfo).Pos(0xc0003a8000, 0xc0000b02a0, 0x11)
	/home/runner/work/ntt/ntt/internal/ntt/parse.go:58 +0x3b
github.com/nokia/ntt/internal/ntt.(*Suite).DefinitionAt(0xc0000b0070, {0xc0000b02a0, 0x62}, 0x6a5ba1, 0x7c6800)
	/home/runner/work/ntt/ntt/internal/ntt/identifier.go:28 +0x68
github.com/nokia/ntt/internal/lsp.(*Server).definition(0xc00009c6e8, {0xa3, 0xb0}, 0xc00009c6c0)
	/home/runner/work/ntt/ntt/internal/lsp/definition.go:24 +0x15b
github.com/nokia/ntt/internal/lsp.(*Server).Definition(0xc0000be000, {0x7be558, 0xc0000b4140}, 0x6ad340)
	/home/runner/work/ntt/ntt/internal/lsp/server_gen.go:32 +0x25
github.com/nokia/ntt/internal/lsp/protocol.serverDispatch({0x7be558, 0xc0000b4140}, {0x7c6a58, 0xc000148380}, 0xc00009a360, {0x7be638, 0xc0000b4100})
	/home/runner/work/ntt/ntt/internal/lsp/protocol/tsserver.go:283 +0x14f7
github.com/nokia/ntt/internal/lsp/protocol.ServerHandler.func1({0x7be558, 0xc0000b4140}, 0xc00009a360, {0x7be638, 0xc0000b4100})
	/home/runner/work/ntt/ntt/internal/lsp/protocol/protocol.go:62 +0x90
github.com/nokia/ntt/internal/lsp/jsonrpc2.MustReplyHandler.func1({0x7be558, 0xc0000b4140}, 0xc0000a8120, {0x7be638, 0xc0000b4100})
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:35 +0xf6
github.com/nokia/ntt/internal/lsp/jsonrpc2.AsyncHandler.func1.2()
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:101 +0x83
created by github.com/nokia/ntt/internal/lsp/jsonrpc2.AsyncHandler.func1
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:99 +0x1a5
[Info  - 5:43:35 PM] Connection to server got closed. Server will restart.
[Error - 5:43:35 PM] Request textDocument/definition failed.
Error: Connection got disposed.
	at Object.dispose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
Scanning "file:///HOMEDIR/WORKSPACE_PATH" for possible TTCN-3 suites
File "file:///HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn" does not belong to any known test suite
Scanning "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" for possible TTCN-3 suites
Could not find a good candidate. Trying "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" recursively and hope for the best.
Adding "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" to list of known test suites
panic: illegal line number for file "/HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn". got=90, max=83

goroutine 21 [running]:
github.com/nokia/ntt/internal/loc.(*File).LineStart(0xc00022ce00, 0x5a)
	/home/runner/work/ntt/ntt/internal/loc/position.go:222 +0x1b9
github.com/nokia/ntt/internal/ntt.(*ParseInfo).Pos(0xc000306000, 0xc00026ce70, 0x12)
	/home/runner/work/ntt/ntt/internal/ntt/parse.go:58 +0x3b
github.com/nokia/ntt/internal/ntt.(*Suite).DefinitionAt(0xc00026cc40, {0xc00026ce70, 0x62}, 0x6a5ba1, 0x7c6800)
	/home/runner/work/ntt/ntt/internal/ntt/identifier.go:28 +0x68
github.com/nokia/ntt/internal/lsp.(*Server).definition(0xc0002a9468, {0xa3, 0xb0}, 0xc0002a9440)
	/home/runner/work/ntt/ntt/internal/lsp/definition.go:24 +0x15b
github.com/nokia/ntt/internal/lsp.(*Server).Definition(0xc00023c2c0, {0x7be558, 0xc00022d3c0}, 0x6ad340)
	/home/runner/work/ntt/ntt/internal/lsp/server_gen.go:32 +0x25
github.com/nokia/ntt/internal/lsp/protocol.serverDispatch({0x7be558, 0xc00022d3c0}, {0x7c6a58, 0xc000148380}, 0xc000304f00, {0x7be638, 0xc00022d380})
	/home/runner/work/ntt/ntt/internal/lsp/protocol/tsserver.go:283 +0x14f7
github.com/nokia/ntt/internal/lsp/protocol.ServerHandler.func1({0x7be558, 0xc00022d3c0}, 0xc000304f00, {0x7be638, 0xc00022d380})
	/home/runner/work/ntt/ntt/internal/lsp/protocol/protocol.go:62 +0x90
github.com/nokia/ntt/internal/lsp/jsonrpc2.MustReplyHandler.func1({0x7be558, 0xc00022d3c0}, 0xc00032c270, {0x7be638, 0xc00022d380})
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:35 +0xf6
github.com/nokia/ntt/internal/lsp/jsonrpc2.AsyncHandler.func1.2()
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:101 +0x83
created by github.com/nokia/ntt/internal/lsp/jsonrpc2.AsyncHandler.func1
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:99 +0x1a5
[Info  - 5:43:35 PM] Connection to server got closed. Server will restart.
[Error - 5:43:35 PM] Request textDocument/definition failed.
Error: Connection got disposed.
	at Object.dispose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
Scanning "file:///HOMEDIR/WORKSPACE_PATH" for possible TTCN-3 suites
File "file:///HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn" does not belong to any known test suite
Scanning "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" for possible TTCN-3 suites
Could not find a good candidate. Trying "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" recursively and hope for the best.
Adding "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" to list of known test suites
panic: illegal line number for file "/HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn". got=90, max=83

goroutine 5 [running]:
github.com/nokia/ntt/internal/loc.(*File).LineStart(0xc0000f0bc0, 0x5a)
	/home/runner/work/ntt/ntt/internal/loc/position.go:222 +0x1b9
github.com/nokia/ntt/internal/ntt.(*ParseInfo).Pos(0xc000220000, 0xc00002c4d0, 0x12)
	/home/runner/work/ntt/ntt/internal/ntt/parse.go:58 +0x3b
github.com/nokia/ntt/internal/ntt.(*Suite).DefinitionAt(0xc00002c2a0, {0xc00002c4d0, 0x62}, 0x6a5ba1, 0x7c6800)
	/home/runner/work/ntt/ntt/internal/ntt/identifier.go:28 +0x68
github.com/nokia/ntt/internal/lsp.(*Server).definition(0xc000264028, {0xa3, 0xb0}, 0xc000264000)
	/home/runner/work/ntt/ntt/internal/lsp/definition.go:24 +0x15b
github.com/nokia/ntt/internal/lsp.(*Server).Definition(0xc00021c160, {0x7be558, 0xc00007a8c0}, 0x6ad340)
	/home/runner/work/ntt/ntt/internal/lsp/server_gen.go:32 +0x25
github.com/nokia/ntt/internal/lsp/protocol.serverDispatch({0x7be558, 0xc00007a8c0}, {0x7c6a58, 0xc0000fe380}, 0xc000244f30, {0x7be638, 0xc00007a880})
	/home/runner/work/ntt/ntt/internal/lsp/protocol/tsserver.go:283 +0x14f7
github.com/nokia/ntt/internal/lsp/protocol.ServerHandler.func1({0x7be558, 0xc00007a8c0}, 0xc000244f30, {0x7be638, 0xc00007a880})
	/home/runner/work/ntt/ntt/internal/lsp/protocol/protocol.go:62 +0x90
github.com/nokia/ntt/internal/lsp/jsonrpc2.MustReplyHandler.func1({0x7be558, 0xc00007a8c0}, 0xc00000f908, {0x7be638, 0xc00007a880})
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:35 +0xf6
github.com/nokia/ntt/internal/lsp/jsonrpc2.AsyncHandler.func1.2()
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:101 +0x83
created by github.com/nokia/ntt/internal/lsp/jsonrpc2.AsyncHandler.func1
	/home/runner/work/ntt/ntt/internal/lsp/jsonrpc2/handler.go:99 +0x1a5
[Info  - 5:43:36 PM] Connection to server got closed. Server will restart.
[Error - 5:43:36 PM] Request textDocument/definition failed.
Error: Connection got disposed.
	at Object.dispose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/HOMEDIR/.vscode-server/extensions/nokia.ttcn3-0.4.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
Scanning "file:///HOMEDIR/WORKSPACE_PATH" for possible TTCN-3 suites
File "file:///HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn" does not belong to any known test suite
Scanning "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" for possible TTCN-3 suites
Could not find a good candidate. Trying "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" recursively and hope for the best.
Adding "/HOMEDIR/WORKSPACE_PATH/SRC/PATH" to list of known test suites
```

**Comment by visstro** [comment]
I somehow totally missed defining the manifest file described on [Getting started
](https://nokia.github.io/ntt/getting-started/) page.
It would be nice if the server failed gracefully on `Could not find a good candidate`.

**Comment by 5nord** [comment]
> It would be nice if the server failed gracefully 

I agree with you 100%. We'll work an that.

I know this bug, but I had no lock reproducing it so far. The language server tries to get the LineStart of line 90, but the file seem to have only 83 lines.
How many lines does the file "file:///HOMEDIR/WORKSPACE_PATH/SRC/PATH/FILENAME.ttcn" have? Do you know if there were syntax-errors in this file?

**Comment by 5nord** [comment]
I have problems reproducing this issue and I am a bit clueless how to fix it.

I am re-designing the algorithm for parsing and goto-definition. Meanwhile I disabled the crash, so you won't be interrupted in your work flow.
